baseURL = "https://cyrivl.github.io"
languageCode = "cn-zh"
title = "My New Hugo Site"
theme="material-design"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "CyrivlClth" # optional
copyright = "© 2021 CyrivlClth"

[params]
  description = "Your Site Description" # optional
  github = "CyrivlClth" # optional
